- name: Installing dnf-automatic
  yum:
    name: "dnf-automatic"
    state: latest
  tags:
    - enableAutoUpdates
    
- name: Fixing Configuration Files
  template:
    src: dnf-automatic.template
    dest: /etc/dnf/automatic.conf
    mode: 0644
    owner: root
    group: root
  tags:
    - enableAutoUpdates
    
- name: Fixing Services
  systemd:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
    daemon_reload: yes
  with_items:
    - { name: "dnf-automatic-install.timer", state: "started", enabled: "yes" }
    - { name: "dnf-automatic-download.timer", state: "started", enabled: "yes" }
  tags:
    - enableAutoUpdates
